import {
  Baby,
  Bike,
  Briefcase,
  Car,
  Cpu,
  Flower2,
  HandHelping,
  Home,
  Monitor,
  PawPrint,
  Shirt,
  Smartphone,
  WashingMachine,
  type LucideIcon,
} from 'lucide-react';

export const categoryIcons: Record<string, LucideIcon> = {
  electronics: Cpu,
  computers: Monitor,
  phones: Smartphone,
  appliances: WashingMachine,
  auto: Car,
  realty: Home,
  hobby: Bike,
  fashion: Shirt,
  'home-garden': Flower2,
  kids: Baby,
  animals: PawPrint,
  services: HandHelping,
  jobs: Briefcase,
};
