/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as ListingsCreateRouteImport } from './routes/listings.create'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as ListingsIdEditRouteImport } from './routes/listings_.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsCreateRoute = ListingsCreateRouteImport.update({
  id: '/listings/create',
  path: '/listings/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdEditRoute = ListingsIdEditRouteImport.update({
  id: '/listings_/$id/edit',
  path: '/listings/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRoute
  '/moderation': typeof ModerationRoute
  '/my-listings': typeof MyListingsRoute
  '/notifications': typeof NotificationsRoute
  '/purchases': typeof PurchasesRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/create': typeof ListingsCreateRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/listings/$id/edit': typeof ListingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRoute
  '/moderation': typeof ModerationRoute
  '/my-listings': typeof MyListingsRoute
  '/notifications': typeof NotificationsRoute
  '/purchases': typeof PurchasesRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/create': typeof ListingsCreateRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/listings/$id/edit': typeof ListingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRoute
  '/moderation': typeof ModerationRoute
  '/my-listings': typeof MyListingsRoute
  '/notifications': typeof NotificationsRoute
  '/purchases': typeof PurchasesRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/create': typeof ListingsCreateRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/listings_/$id/edit': typeof ListingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/auth'
    | '/catalog'
    | '/favorites'
    | '/messages'
    | '/moderation'
    | '/my-listings'
    | '/notifications'
    | '/purchases'
    | '/sales'
    | '/settings'
    | '/listings/$id'
    | '/listings/create'
    | '/profile/$username'
    | '/listings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/auth'
    | '/catalog'
    | '/favorites'
    | '/messages'
    | '/moderation'
    | '/my-listings'
    | '/notifications'
    | '/purchases'
    | '/sales'
    | '/settings'
    | '/listings/$id'
    | '/listings/create'
    | '/profile/$username'
    | '/listings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/auth'
    | '/catalog'
    | '/favorites'
    | '/messages'
    | '/moderation'
    | '/my-listings'
    | '/notifications'
    | '/purchases'
    | '/sales'
    | '/settings'
    | '/listings/$id'
    | '/listings/create'
    | '/profile/$username'
    | '/listings_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRoute
  CatalogRoute: typeof CatalogRoute
  FavoritesRoute: typeof FavoritesRoute
  MessagesRoute: typeof MessagesRoute
  ModerationRoute: typeof ModerationRoute
  MyListingsRoute: typeof MyListingsRoute
  NotificationsRoute: typeof NotificationsRoute
  PurchasesRoute: typeof PurchasesRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  ListingsIdRoute: typeof ListingsIdRoute
  ListingsCreateRoute: typeof ListingsCreateRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ListingsIdEditRoute: typeof ListingsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings': {
      id: '/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/create': {
      id: '/listings/create'
      path: '/listings/create'
      fullPath: '/listings/create'
      preLoaderRoute: typeof ListingsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings_/$id/edit': {
      id: '/listings_/$id/edit'
      path: '/listings/$id/edit'
      fullPath: '/listings/$id/edit'
      preLoaderRoute: typeof ListingsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthRoute: AuthRoute,
  CatalogRoute: CatalogRoute,
  FavoritesRoute: FavoritesRoute,
  MessagesRoute: MessagesRoute,
  ModerationRoute: ModerationRoute,
  MyListingsRoute: MyListingsRoute,
  NotificationsRoute: NotificationsRoute,
  PurchasesRoute: PurchasesRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  ListingsIdRoute: ListingsIdRoute,
  ListingsCreateRoute: ListingsCreateRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ListingsIdEditRoute: ListingsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
