export const LAPTOP_FALLBACK = [
  {
    name: 'Apple',
    models: [
      'MacBook Air M2',
      'MacBook Air M3',
      'MacBook Air 15 M3',
      'MacBook Pro 14 M3',
      'MacBook Pro 16 M3',
      'MacBook Pro 14 M4',
      'MacBook Pro 16 M4',
    ],
  },
  {
    name: 'Lenovo',
    models: [
      'ThinkPad E14',
      'ThinkPad T14',
      'ThinkPad X1 Carbon',
      'IdeaPad Slim 3',
      'IdeaPad Slim 5',
      'Legion 5',
      'Legion Pro 5',
      'LOQ 15',
      'Yoga 7 14',
    ],
  },
  {
    name: 'HP',
    models: [
      'Pavilion 15',
      'Pavilion Plus 14',
      'Victus 16',
      'EliteBook 840',
      'EliteBook 860',
      'Omen 16',
      'Omen Transcend 14',
      'Envy x360 15',
      'ProBook 450 G10',
    ],
  },
  {
    name: 'Dell',
    models: [
      'Inspiron 15',
      'Inspiron 16',
      'XPS 13',
      'XPS 14',
      'XPS 15',
      'XPS 16',
      'G15',
      'G16',
      'Latitude 5540',
      'Alienware m16',
    ],
  },
  {
    name: 'Acer',
    models: [
      'Aspire 5',
      'Aspire 3',
      'Swift Go 14',
      'Swift X 14',
      'Nitro V 15',
      'Nitro 16',
      'Predator Helios 16',
      'Predator Helios Neo 16',
    ],
  },
  {
    name: 'ASUS',
    models: [
      'Vivobook 15',
      'Vivobook S 15',
      'Zenbook 14',
      'Zenbook 14 OLED',
      'TUF Gaming A15',
      'TUF Gaming F15',
      'ROG Zephyrus G14',
      'ROG Strix G16',
      'ProArt P16',
    ],
  },
  {
    name: 'MSI',
    models: [
      'Modern 14',
      'Thin GF63',
      'Cyborg 15',
      'Katana 15',
      'Stealth 14',
      'Stealth 16',
      'Raider GE78',
      'Vector GP68',
    ],
  },
  {
    name: 'Samsung',
    models: ['Galaxy Book4', 'Galaxy Book4 Pro', 'Galaxy Book4 Ultra', 'Galaxy Book4 Edge'],
  },
  { name: 'Huawei', models: ['MateBook D16', 'MateBook 14', 'MateBook X Pro'] },
  { name: 'Honor', models: ['MagicBook X16', 'MagicBook 14', 'MagicBook Pro 16'] },
  {
    name: 'Microsoft',
    models: [
      'Surface Laptop 5',
      'Surface Laptop 6',
      'Surface Laptop Go 3',
      'Surface Laptop Studio 2',
    ],
  },
  { name: 'Razer', models: ['Blade 14', 'Blade 16', 'Blade 18'] },
  { name: 'Gigabyte', models: ['G5', 'G6', 'Aero 16', 'Aorus 16X'] },
] as const;

export const DESKTOP_FALLBACK = [
  {
    name: 'Apple',
    models: [
      'Mac mini M2',
      'Mac mini M4',
      'iMac 24 M3',
      'Mac Studio M2 Max',
      'Mac Studio M2 Ultra',
      'Mac Pro',
    ],
  },
  {
    name: 'HP',
    models: [
      'Pavilion Desktop',
      'Pavilion Plus Desktop',
      'OMEN 25L',
      'OMEN 45L',
      'EliteDesk 800 G9',
    ],
  },
  {
    name: 'Dell',
    models: [
      'OptiPlex 7010',
      'OptiPlex Micro Plus',
      'XPS Desktop',
      'Alienware Aurora R16',
      'Inspiron Desktop',
    ],
  },
  {
    name: 'Lenovo',
    models: [
      'ThinkCentre M70q',
      'ThinkCentre M90q',
      'Legion Tower 5',
      'Legion Tower 7i',
      'IdeaCentre AIO 27',
    ],
  },
  { name: 'ASUS', models: ['ExpertCenter D5', 'ExpertCenter P500', 'ROG G16CH', 'ROG Strix GA15'] },
  { name: 'Acer', models: ['Aspire TC', 'Predator Orion 7000', 'Veriton X'] },
  { name: 'MSI', models: ['PRO DP21', 'MAG Infinite S3', 'MEG Trident X2', 'Aegis RS'] },
  { name: 'Corsair', models: ['Vengeance i7500', 'Vengeance a8200', 'One i300'] },
] as const;

export const PC_PARTS_FALLBACK = [
  {
    name: 'AMD',
    models: [
      'Ryzen 5 5600',
      'Ryzen 5 5600X',
      'Ryzen 5 7600',
      'Ryzen 5 7600X',
      'Ryzen 7 5700X',
      'Ryzen 7 5800X3D',
      'Ryzen 7 7700X',
      'Ryzen 7 7800X3D',
      'Ryzen 9 7900X',
      'Ryzen 9 7950X3D',
    ],
  },
  {
    name: 'Intel',
    models: [
      'Core i5-12400F',
      'Core i5-13400F',
      'Core i5-14600K',
      'Core i7-13700K',
      'Core i7-14700K',
      'Core i9-13900K',
      'Core i9-14900K',
      'Core Ultra 5 245K',
      'Core Ultra 7 265K',
      'Core Ultra 9 285K',
    ],
  },
  {
    name: 'NVIDIA',
    models: [
      'GeForce RTX 4060',
      'GeForce RTX 4060 Ti',
      'GeForce RTX 4070',
      'GeForce RTX 4070 Super',
      'GeForce RTX 4070 Ti Super',
      'GeForce RTX 4080 Super',
      'GeForce RTX 4090',
      'GeForce RTX 5060',
      'GeForce RTX 5070',
      'GeForce RTX 5080',
    ],
  },
  {
    name: 'ASUS',
    models: [
      'ROG Strix B550-F',
      'TUF Gaming B650-Plus',
      'ROG Strix X670E-E',
      'ROG Strix RTX 4070',
      'ROG Strix RTX 4080',
      'TUF Gaming RTX 4060 Ti',
    ],
  },
  {
    name: 'MSI',
    models: [
      'MAG B550 Tomahawk',
      'PRO B650-P WiFi',
      'MAG X670E Tomahawk',
      'GeForce RTX 4060 Ventus',
      'GeForce RTX 4070 Super Ventus',
      'MPG B650 Carbon WiFi',
    ],
  },
  {
    name: 'Gigabyte',
    models: [
      'B550 Aorus Elite',
      'B650 Eagle AX',
      'X670 Aorus Elite AX',
      'GeForce RTX 4070 Windforce',
      'GeForce RTX 4080 Gaming OC',
      'Aorus RTX 4090 Master',
    ],
  },
  {
    name: 'Corsair',
    models: [
      'Vengeance 32GB DDR5',
      'Vengeance LPX 16GB',
      'Vengeance RGB 32GB',
      'RM750x',
      'RM850x',
      'HX1000i',
      '4000D Airflow',
      '5000D Airflow',
      '7000D Airflow',
    ],
  },
  {
    name: 'Kingston',
    models: [
      'Fury Beast 16GB',
      'Fury Beast 32GB',
      'Fury Renegade 32GB DDR5',
      'NV2 1TB',
      'KC3000 2TB',
      'Fury Renegade 4TB',
    ],
  },
  {
    name: 'Samsung',
    models: ['990 EVO 1TB', '990 EVO Plus 2TB', '990 PRO 1TB', '990 PRO 2TB', '870 EVO 1TB'],
  },
  {
    name: 'Western Digital',
    models: [
      'Blue SN580 1TB',
      'Black SN850X 1TB',
      'Black SN850X 2TB',
      'Blue 2TB HDD',
      'Red Plus 4TB',
    ],
  },
  {
    name: 'Seagate',
    models: [
      'Barracuda 2TB',
      'Barracuda 4TB',
      'IronWolf 4TB',
      'IronWolf Pro 8TB',
      'FireCuda 530 1TB',
    ],
  },
  {
    name: 'Crucial',
    models: ['P3 Plus 1TB', 'P5 Plus 2TB', 'T500 2TB', 'Ballistix 32GB DDR4', 'Pro DDR5 32GB'],
  },
  {
    name: 'be quiet!',
    models: [
      'Pure Rock 2',
      'Dark Rock Pro 4',
      'Dark Rock Pro 5',
      'Pure Base 500DX',
      'Shadow Base 800 FX',
    ],
  },
  { name: 'Noctua', models: ['NH-D15', 'NH-U12S', 'NH-L9i', 'NF-A12x25 PWM'] },
  { name: 'DeepCool', models: ['AK620', 'AK400', 'LS720', 'MATREXX 55', 'CH560'] },
  { name: 'Arctic', models: ['Freezer 34 eSports', 'Liquid Freezer II 360', 'P12 PWM'] },
  { name: 'TeamGroup', models: ['T-Force Delta 32GB DDR5', 'T-Force Cardea Z44L 1TB', 'MP33 1TB'] },
  { name: 'ADATA', models: ['Legend 850 1TB', 'Legend 960 2TB', 'XPG Lancer 32GB DDR5'] },
  {
    name: 'Cooler Master',
    models: ['Hyper 212 Black', 'MasterLiquid ML240L', 'MasterBox TD500', 'MasterBox 600'],
  },
  { name: 'NZXT', models: ['Kraken 240', 'Kraken 360', 'H5 Flow', 'H7 Flow', 'C850 Gold'] },
] as const;
